config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'quizzes#index'

  get 'signup' => 'users#new', as: :signup
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy', as: :logout

  post 'quizzes/:id/check' => 'quizzes#check'

  resources :quizzes do
    resources :questions
  end

  resources :questions do
    resources :answers
  end

  get 'results' => 'completed_quizzes#new', as: :new_results
  post 'results' => 'completed_quizzes#create'
  get 'results/:id' => 'completed_quizzes#show', as: :score


end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/completed_quiz.rb
class CompletedQuiz < ApplicationRecord
  belongs_to :quiz
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  has_many :answers

  validates :body, presence: true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :questions
  has_many :completed_quizzes
  validates :title, presence: true
  validates :description, presence: true

  scope :published, -> { where(published: true)}
  scope :unpublished, -> { where(published: false)}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :completed_quizzes
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action do
    @question = Question.find(params[:question_id])
  end

  def index

  end

  def new
    @answer = Answer.new
  end

  def create
    puts request.params[:answer][:correct]
    @quiz = Quiz.find(@question.quiz_id)
    @answer = Answer.new
    @answer.body = params[:answer][:body]
    if params[:answer][:correct] == "true"
      @answer.correct = true
    elsif params[:answer][:correct] == "false"
      puts "answer is false"
      @answer.correct = false
    end
    @answer.question_id = params[:question_id]
    if @answer.save
      redirect_to edit_quiz_question_path(@quiz, @question)
    else
      render :new
    end
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @quiz = Quiz.find(@question.quiz_id)
    @answer = Answer.find(params[:id])
    @answer.body = params[:answer][:body]
    @answer.correct = params[:answer][:correct]
    @answer.question_id = params[:question_id]
    if @answer.save
      redirect_to edit_quiz_question_path(@quiz, @question)
    else
      render :new
    end
  end

  def destroy
    @quiz = Quiz.find(@question.quiz_id)
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to edit_quiz_question_path(@quiz, @question)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end
end

app/controllers/completed_quizzes_controller.rb
class CompletedQuizzesController < ApplicationController

  def new
    @completed_quiz = CompletedQuiz.new
  end

  def create
    @completed_quiz = CompletedQuiz.new
    @completed_quiz.quiz_id = session[:quiz]
    @completed_quiz.user_id = session[:user_id]
    @completed_quiz.score = session[:correct]
    @completed_quiz.save
    redirect_to score_path(@completed_quiz)
  end

  def show
    @completed_quiz = CompletedQuiz.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action do
    @quiz = Quiz.find(params[:quiz_id])
  end

  def index
    @questions = @quiz.questions
  end

  def new
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new
    @question.body = params[:question][:body]
    @question.quiz_id = params[:quiz_id]
    if @question.save
      redirect_to edit_quiz_path(@quiz)
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.body = params[:question][:body]
    if @question.save
      redirect_to quiz_path(@quiz)
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to quiz_path(@quiz)
  end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  before_action do
    if @current_user.blank?
      redirect_to login_path
    end
  end

  def index
    session[:quiz] = nil
      @published_quizzes = Quiz.published.select do |quiz|
        quiz.completed_quizzes.where(user_id: @current_user.id).exists? == false
      end
      @unpublished_quizzes = Quiz.unpublished
    @completed_quizzes = @current_user.completed_quizzes
    @scores = @completed_quizzes.map do |quiz|
      quiz.score
    end
    @total_score = @scores.sum
  end

  def show
    if session[:quiz] == nil
      session[:quiz] = params[:id]
      questions = Question.where(quiz_id: session[:quiz]).map do |question|
        question.id
      end
      session[:questions] = questions.shuffle
      session[:correct] = 0
    end

    @quiz = Quiz.find(params[:id])
    @question_id = session[:questions].pop
    @question = Question.find(@question_id)
    @answers = @question.answers.shuffle
  end

  def check
    @quiz = Quiz.find(params[:id])
    @answer = Answer.find(params[:answer])
    if @answer.correct == true
      session[:correct] += 1
    end
    if session[:questions].length == 0
      redirect_to new_results_path
    else
      redirect_to quiz_path(@quiz)
    end
  end

  def new
    @quiz = Quiz.new
  end

  def create
    @quiz = Quiz.new
    @quiz.title = params[:quiz][:title]
    @quiz.description = params[:quiz][:description]
    if @quiz.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @quiz = Quiz.find(params[:id])
    if @quiz.published == true
      redirect_to root_path, notice: "Quiz can no longer be edited"
    end
  end

  def update
    puts params
    @quiz = Quiz.find(params[:id])
    if @quiz.published == true
      redirect_to root_path, notice: "Quiz can no longer be edited"
    else
      @quiz.title = params[:quiz][:title]
      @quiz.description = params[:quiz][:description]
      @quiz.published = params[:quiz][:published]
      if @quiz.save
        redirect_to root_path
      else
        render :edit
      end
    end
  end

  def destroy
    @quiz = Quiz.find(params[:id])
    @quiz.destroy
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    username = params[:username]
    password = params[:password]
    user = User.find_by username: username
    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to root_path, notice: "Welcome #{user.username}"
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Account created!"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/completed_quizzes_helper.rb
module CompletedQuizzesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<% if @answer.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

    <ul>
    <% @answer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for([@question, @answer]) do |f| %>

<div class="input">
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>

<div class="input">
  <p>Is this the correct answer?</p>
  <%= f.radio_button :correct, "true" %>
  <%= f.label :correct, "true" %>
  <%= f.radio_button :correct, "false" %>
  <%= f.label :correct, "false" %>
</div>

<div class="input">
  <%= f.submit %>
</div>

<% end %>

app/views/answers/edit.html.erb
<div class="answer">
  <h3>Edit Answer</h3>

  <%= render partial: 'form' %>
</div>

app/views/answers/new.html.erb
<div class="answer">
  <h3>Add Answer</h3>

  <%= render partial: 'form' %>
</div>

app/views/completed_quizzes/new.html.erb
<div class="results">
  <h3>You finished the quiz!</h3>


  <%= form_tag do %>
  <%= submit_tag "See your score" %>
  <% end %>
</div>

app/views/completed_quizzes/show.html.erb
<div class="results">
  <h3>You got <%= @completed_quiz.score %> out of <%= @completed_quiz.quiz.questions.length %> right!</h3>

  <%= link_to "Take another Quiz", root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizShow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to 'Quiz', root_path %></h1>
      <nav>
        <% if @current_user == nil %>
          <p><%= link_to 'Login', login_path %></p>
          <p><%= link_to 'Sign Up', signup_path %></p>
        <% else %>
          <% if @current_user.admin == true %>
            <p><%= link_to 'Admin', rails_admin_path %></p>
            <p><%= link_to 'Create Quiz', new_quiz_path %></p>
          <% end %>
            <p><%= link_to 'Sign Out', logout_path, method: :delete %></p>
        <% end %>
      </nav>
    </header>
    <div class="container">

      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for([@quiz, @question]) do |f| %>

<div class="input">
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>

<div class="input">
  <%= f.submit %>
</div>

<% end %>

app/views/questions/edit.html.erb
<div class="question">
  <h3><%= @quiz.title %></h3>

  <h4>Edit Question</h4>

  <%= render partial: 'form' %>

  <h4>Answers:</h4>

  <%= link_to "Add Answer", new_question_answer_path(@question) %>

  <% @question.answers.each do |answer| %>

  <p><%= answer.body %></p>
  <p>Correct? <%= answer.correct %></p>
  <%= link_to "Edit", edit_question_answer_path(@question, answer) %>
  <%= link_to "Delete", question_answer_path(@question, answer), method: :delete, data: {confirm: "Are you sure you want to delete this answer?"} %>

  <% end %>
</div>

app/views/questions/index.html.erb
<h3><%= @quiz.title %></h3>

<%= @questions.each do |question| %>

<p><%= question.body %></p>

<% end %>

app/views/questions/new.html.erb
<div class="question">
  <h3><%= link_to @quiz.title, quiz_path(@quiz) %></h3>

  <h3>Add Question</h3>

  <%= render partial: 'form' %>
</div>

app/views/quizzes/_form.html.erb
<%= form_for @quiz do |f| %>
<div class="input">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div class="input">
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>

<div class="input">
  <p>Publish?</p>
  <%= f.radio_button :published, "true" %>
  <%= f.label :published, "true" %>
  <%= f.radio_button :published, "false" %>
  <%= f.label :published, "false" %>
</div>

<div class="input">
  <%= f.submit %>
</div>

<% end %>

app/views/quizzes/edit.html.erb
<div class="quiz">
  <h3>Edit Quiz</h3>

  <%= render partial: 'form' %>

  <%= link_to 'Add Question', new_quiz_question_path(@quiz) %>
  <% @quiz.questions.each do |question| %>

  <p><%= question.body %></p>
  <%= link_to 'Edit', edit_quiz_question_path(@quiz, question) %>
  <%= link_to 'Delete', quiz_question_path(@quiz, question), method: :delete, data: {confirm: "Are you sure you want to delete this question?"} %>
  <% end %>
</div>

app/views/quizzes/index.html.erb
<div class="quizzes">
  <div class="published">
    <% if @published_quizzes.length == 0 %>
      <h4>There are no new quizzes to take.  Check back soon!</h3>
    <% else %>
      <% @published_quizzes.each do |quiz| %>
        <h3><%= link_to quiz.title, quiz_path(quiz) %></h3>
        <h4><%= quiz.description %></h4>
        <h5><%= quiz.questions.length %> Questions</h5>
      <% end %>
    <% end %>
  </div>
  <% if @current_user.admin == true %>
  <div class="unpublished">
    <h2>Unpublished Quizzes</h2>
    <% @unpublished_quizzes.each do |quiz| %>
    <h3><%= quiz.title %></h3>
    <h4><%= quiz.description %></h4>
    <h5><%= quiz.questions.length %> Questions</h5>
    <%= link_to 'Edit', edit_quiz_path(quiz) %>
    <%= link_to 'Delete', quiz_path(quiz), method: :delete, data: {confirm: "Are you sure you want to delete this quiz?"} %>
    <% end %>
  </div>
  <% end %>
</div>



<aside class="well">
  <h3>Completed Quizzes</h3>
  <h4>Total Score: <%= @total_score %></h4>
  <% @completed_quizzes.each do |quiz| %>
  <div class="">
    <%= quiz.quiz.title %>
    <%= quiz.score %>/<%= quiz.quiz.questions.length %>
  </div>
    <% end %>
</aside>

app/views/quizzes/new.html.erb
<div class="quiz">
  <h3>Create new quiz!</h3>

  <%= render partial: 'form' %>
</div>

app/views/quizzes/show.html.erb
<div class="quiz">
  <h3><%= @quiz.title %></h3>
  <h4><%= @quiz.description %></h4>

  <p><%= @question.body %></p>
  <%= form_tag({controller: "quizzes", action: "check"}, method: "post") do %>
  <% @answers.each do |answer| %>
  <div class="">
    <%= radio_button_tag(:answer, answer.id) %>
    <%= label_tag(:answer, answer.body) %>
  </div>
  <% end %>
  <%= submit_tag "Submit Answer" %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="">
  <% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>
  <div class="well">
    <h3>Sign up!</h3>
    <%= form_for @user, url: signup_path do |f| %>

    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, placeholder: "Enter Username" %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, placeholder: "Enter Password" %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
    </div>

    <%= f.submit "Sign up!", class: "btn btn-primary"%>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
hello @user.username

<%= notice %>